[90m[main 2025-02-25T16:14:14.451Z][0m update#setState disabled
[90m[main 2025-02-25T16:14:14.452Z][0m update#ctor - updates are disabled as there is no update URL
[645366:0225/214417.088786:ERROR:nss_util.cc(345)] After loading Root Certs, loaded==false: NSS error code: -8018
[90m[main 2025-02-25T19:22:06.821Z][0m Extension host with pid 646219 exited with code: 15, signal: unknown.
[91m[main 2025-02-25T19:22:06.823Z][0m [UtilityProcess id: 2, type: extensionHost, pid: 646219]: crashed with code 15 and reason 'killed'
[91m[main 2025-02-25T19:22:06.971Z][0m ptyHost terminated unexpectedly with code 0
[93m[main 2025-02-25T19:22:06.980Z][0m [UtilityProcess type: ptyHost, pid: 646609]: unable to kill the process
[90m[main 2025-03-19T10:26:26.102Z][0m updateURL https://api2.cursor.sh/updates/api/update/linux-x64/cursor/0.45.14/48e0812a9cbfa4229f7590ae6e75cdc278351bb83dd94efa41f67295b09d21e6
[90m[main 2025-03-19T10:26:26.103Z][0m update#setState idle
[65598:0319/155628.642912:ERROR:nss_util.cc(345)] After loading Root Certs, loaded==false: NSS error code: -8018
[90m[main 2025-03-19T10:26:56.104Z][0m update#setState checking for updates
[90m[main 2025-03-19T10:26:56.420Z][0m update#setState ready
[91m[main 2025-03-19T22:48:32.971Z][0m ptyHost terminated unexpectedly with code 15
[93m[main 2025-03-19T22:48:32.972Z][0m [UtilityProcess type: ptyHost, pid: 66906]: unable to kill the process
[65598:0320/041833.005537:ERROR:network_service_instance_impl.cc(608)] Network service crashed, restarting service.
LaunchProcess: failed to execvp:
/proc/self/exe
[90m[main 2025-03-19T22:48:33.050Z][0m Extension host with pid 66522 exited with code: 15, signal: unknown.
[91m[main 2025-03-19T22:48:33.051Z][0m [UtilityProcess id: 2, type: extensionHost, pid: 66522]: crashed with code 15 and reason 'killed'
[91m[main 2025-03-19T22:48:33.054Z][0m ptyHost terminated unexpectedly with code 32512
[93m[main 2025-03-19T22:48:33.055Z][0m [UtilityProcess type: ptyHost, pid: 1509022]: unable to kill the process
[91m[main 2025-03-19T22:48:33.058Z][0m [UtilityProcess type: shared-process, pid: 66402]: crashed with code 15 and reason 'killed'
[65598:0320/041833.072966:ERROR:zygote_communication_linux.cc(297)] Failed to send GetTerminationStatus message to zygote
[65598:0320/041833.076565:ERROR:network_service_instance_impl.cc(608)] Network service crashed, restarting service.
[90m[main 2025-03-20T16:00:04.986Z][0m updateURL https://api2.cursor.sh/updates/api/update/linux-x64/cursor/0.45.14/48e0812a9cbfa4229f7590ae6e75cdc278351bb83dd94efa41f67295b09d21e6
[90m[main 2025-03-20T16:00:04.987Z][0m update#setState idle
[11800:0320/213007.173359:ERROR:nss_util.cc(345)] After loading Root Certs, loaded==false: NSS error code: -8018
[90m[main 2025-03-20T16:00:34.988Z][0m update#setState checking for updates
[90m[main 2025-03-20T16:00:35.271Z][0m update#setState ready
[90m[main 2025-03-20T16:01:42.202Z][0m Extension host with pid 15682 exited with code: 0, signal: unknown.
[90m[main 2025-03-20T16:01:42.321Z][0m Extension host with pid 15582 exited with code: 0, signal: unknown.
[91m[main 2025-03-20T16:01:42.364Z][0m [UtilityProcess id: 2, type: fileWatcher, pid: 15566]: crashed with code 15 and reason 'killed'
[91m[main 2025-03-20T22:12:40.801Z][0m ptyHost terminated unexpectedly with code 15
[93m[main 2025-03-20T22:12:40.802Z][0m [UtilityProcess type: ptyHost, pid: 17881]: unable to kill the process
[11800:0321/034240.806021:FATAL:electron_browser_main_parts.cc(504)] Failed to shutdown.
[90m[main 2025-03-21T08:58:31.836Z][0m updateURL https://api2.cursor.sh/updates/api/update/linux-x64/cursor/0.45.14/48e0812a9cbfa4229f7590ae6e75cdc278351bb83dd94efa41f67295b09d21e6
[90m[main 2025-03-21T08:58:31.837Z][0m update#setState idle
FetchError: request to https://api2.cursor.sh/aiserver.v1.AuthService/DownloadUpdate failed, reason: 
    at ClientRequest.<anonymous> (/tmp/.mount_cursornAAyrU/resources/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketErrorListener (node:_http_client:504:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
[9915:0321/142835.104429:ERROR:nss_util.cc(345)] After loading Root Certs, loaded==false: NSS error code: -8018
[90m[main 2025-03-21T08:59:01.838Z][0m update#setState checking for updates
[90m[main 2025-03-21T08:59:02.108Z][0m update#setState ready
[9915:0321/215007.321693:ERROR:atom_cache.cc(230)] Add chromium/from-privileged to kAtomsToCache
[90m[main 2025-03-22T16:20:02.113Z][0m updateURL https://api2.cursor.sh/updates/api/update/linux-x64/cursor/0.45.14/48e0812a9cbfa4229f7590ae6e75cdc278351bb83dd94efa41f67295b09d21e6
[90m[main 2025-03-22T16:20:02.114Z][0m update#setState idle
[39128:0322/215008.481700:ERROR:nss_util.cc(345)] After loading Root Certs, loaded==false: NSS error code: -8018
[39246:0322/215021.901767:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215021.990701:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215025.216494:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215025.384470:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215025.409053:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215025.409632:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215025.410011:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215027.340340:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215028.837045:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215031.837061:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[90m[main 2025-03-22T16:20:32.118Z][0m update#setState checking for updates
[39246:0322/215034.060802:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215034.071344:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215034.071728:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[90m[main 2025-03-22T16:20:37.570Z][0m update#setState ready
[39246:0322/215038.298876:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215040.623380:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
[39246:0322/215046.002277:ERROR:ssl_client_socket_impl.cc(882)] handshake failed; returned -1, SSL error code 1, net_error -100
FetchError: request to https://api2.cursor.sh/aiserver.v1.AuthService/DownloadUpdate failed, reason: getaddrinfo EAI_AGAIN api2.cursor.sh
    at ClientRequest.<anonymous> (/tmp/.mount_cursoriPM9RS/resources/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketErrorListener (node:_http_client:504:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'EAI_AGAIN',
  code: 'EAI_AGAIN'
}
FetchError: request to https://api2.cursor.sh/aiserver.v1.AuthService/DownloadUpdate failed, reason: 
    at ClientRequest.<anonymous> (/tmp/.mount_cursoriPM9RS/resources/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketErrorListener (node:_http_client:504:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ENETUNREACH',
  code: 'ENETUNREACH'
}
FetchError: request to https://api2.cursor.sh/aiserver.v1.AuthService/DownloadUpdate failed, reason: 
    at ClientRequest.<anonymous> (/tmp/.mount_cursoriPM9RS/resources/app/node_modules/node-fetch/lib/index.js:1501:11)
    at ClientRequest.emit (node:events:518:28)
    at emitErrorEvent (node:_http_client:101:11)
    at TLSSocket.socketErrorListener (node:_http_client:504:5)
    at TLSSocket.emit (node:events:518:28)
    at emitErrorNT (node:internal/streams/destroy:169:8)
    at emitErrorCloseNT (node:internal/streams/destroy:128:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  type: 'system',
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT'
}
